
// HOUSE TYPES
export const CREATE_HOUSE = 'CREATE_HOUSE';
export const CREATE_HOUSE_SUCCESS = 'CREATE_HOUSE_SUCCESS';
export const CREATE_HOUSE_FAIL ='CREATE_HOUSE_FAIL';


// MEMEBER TYPES
export const CREATE_MEMEBER = 'CREATE_MEMEBER';
export const CREATE_MEMEBER_SUCCESS = 'CREATE_MEMEBER_SUCCESS';
export const CREATE_MEMEBER_FAIL ='CREATE_MEMEBER_FAIL';
